// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mock;

#nullable disable

namespace Mock.Migrations
{
    [DbContext(typeof(SmartMatchDbContext))]
    partial class SmartMatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnglishLevel")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Repository.Entities.CandidateRequirement", b =>
                {
                    b.Property<int>("CandidateReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateReqId"));

                    b.Property<int>("AdvantageOrMust")
                        .HasColumnType("int");

                    b.Property<int>("IdCandidate")
                        .HasColumnType("int");

                    b.Property<int>("IdRequirement")
                        .HasColumnType("int");

                    b.HasKey("CandidateReqId");

                    b.HasIndex("IdCandidate");

                    b.HasIndex("IdRequirement");

                    b.ToTable("CandidateRequirements");
                });

            modelBuilder.Entity("Repository.Entities.CandidateSkills", b =>
                {
                    b.Property<int>("CandidateSkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateSkillsId"));

                    b.Property<int>("IdCandidate")
                        .HasColumnType("int");

                    b.Property<int>("IdSkills")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuccessRate")
                        .HasColumnType("int");

                    b.HasKey("CandidateSkillsId");

                    b.HasIndex("IdCandidate");

                    b.HasIndex("IdSkills");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("Repository.Entities.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnglishLevel")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("NumCandidate")
                        .HasColumnType("int");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Repository.Entities.JobRequirement", b =>
                {
                    b.Property<int>("JobRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobRequirementId"));

                    b.Property<string>("AdvantageOrMust")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdJob")
                        .HasColumnType("int");

                    b.Property<int>("IdRequirement")
                        .HasColumnType("int");

                    b.HasKey("JobRequirementId");

                    b.HasIndex("IdJob");

                    b.HasIndex("IdRequirement");

                    b.ToTable("JobRequirements");
                });

            modelBuilder.Entity("Repository.Entities.JobSkills", b =>
                {
                    b.Property<int>("JobSkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobSkillsId"));

                    b.Property<int>("IdJob")
                        .HasColumnType("int");

                    b.Property<int>("IdSkills")
                        .HasColumnType("int");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobSkillsId");

                    b.HasIndex("IdJob");

                    b.HasIndex("IdSkills");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("Repository.Entities.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Repository.Entities.Requirements", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequirementId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("Repository.Entities.Skills", b =>
                {
                    b.Property<int>("SkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillsId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Repository.Entities.CandidateRequirement", b =>
                {
                    b.HasOne("Repository.Entities.Candidate", "Candidate")
                        .WithMany("ListCandidateRequirement")
                        .HasForeignKey("IdCandidate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Requirements", "Requirement")
                        .WithMany()
                        .HasForeignKey("IdRequirement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Repository.Entities.CandidateSkills", b =>
                {
                    b.HasOne("Repository.Entities.Candidate", "Candidate")
                        .WithMany("ListSkills")
                        .HasForeignKey("IdCandidate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Skills", "Skills")
                        .WithMany()
                        .HasForeignKey("IdSkills")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Repository.Entities.Job", b =>
                {
                    b.HasOne("Repository.Entities.Manager", "Manager")
                        .WithMany("Jobs")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Repository.Entities.JobRequirement", b =>
                {
                    b.HasOne("Repository.Entities.Job", "Job")
                        .WithMany("ListRequirement")
                        .HasForeignKey("IdJob")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Requirements", "Requirement")
                        .WithMany()
                        .HasForeignKey("IdRequirement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Repository.Entities.JobSkills", b =>
                {
                    b.HasOne("Repository.Entities.Job", "Job")
                        .WithMany("ListSkills")
                        .HasForeignKey("IdJob")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Skills", "Skills")
                        .WithMany()
                        .HasForeignKey("IdSkills")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Repository.Entities.Candidate", b =>
                {
                    b.Navigation("ListCandidateRequirement");

                    b.Navigation("ListSkills");
                });

            modelBuilder.Entity("Repository.Entities.Job", b =>
                {
                    b.Navigation("ListRequirement");

                    b.Navigation("ListSkills");
                });

            modelBuilder.Entity("Repository.Entities.Manager", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
